name: Build WPF App
on:
  workflow_dispatch:
jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.x
    - name: Download & install Scoop
      run: | 
          iex "& {$(irm get.scoop.sh)} -RunAsAdmin"
          Join-Path (Resolve-Path ~).Path "scoop\shims" >> $Env:GITHUB_PATH
          scoop bucket add extras
    - name: Download & install dependencies
      run: scoop install inno-setup 7zip

    - name: Build
      run: dotnet build JboxTransfer.WPF/JboxTransfer.WPF.csproj -c Release -f net7.0-windows
    - name: Delete Extra Files
      run: |
          Remove-Item -Force -Recurse -Path "./JboxTransfer.WPF/bin/Release/net7.0-windows/runtimes/alpine-x64"
          Remove-Item -Force -Recurse -Path "./JboxTransfer.WPF/bin/Release/net7.0-windows/runtimes/linux-arm"
          Remove-Item -Force -Recurse -Path "./JboxTransfer.WPF/bin/Release/net7.0-windows/runtimes/linux-arm64"
          Remove-Item -Force -Recurse -Path "./JboxTransfer.WPF/bin/Release/net7.0-windows/runtimes/linux-armel"
          Remove-Item -Force -Recurse -Path "./JboxTransfer.WPF/bin/Release/net7.0-windows/runtimes/linux-mips64"
          Remove-Item -Force -Recurse -Path "./JboxTransfer.WPF/bin/Release/net7.0-windows/runtimes/linux-musl-x64"
          Remove-Item -Force -Recurse -Path "./JboxTransfer.WPF/bin/Release/net7.0-windows/runtimes/linux-x64"
          Remove-Item -Force -Recurse -Path "./JboxTransfer.WPF/bin/Release/net7.0-windows/runtimes/linux-x86"
          Remove-Item -Force -Recurse -Path "./JboxTransfer.WPF/bin/Release/net7.0-windows/runtimes/osx-x64"
          Remove-Item -Force -Recurse -Path "./JboxTransfer.WPF/bin/Release/net7.0-windows/runtimes/win-arm"
          Remove-Item -Force -Recurse -Path "./JboxTransfer.WPF/bin/Release/net7.0-windows/runtimes/win-arm64"
    - name: Pack
      run: iscc ./Installer/jboxtransfer.iss

    - name: Upload jboxtransfer-x64-installer-online
      uses: actions/upload-artifact@v3
      with:
        name: jboxtransfer-x64-installer-online
        path: ./Installer/jboxtransfer-x64-installer-online.exe

    - name: Upload jboxtransfer-x64-portable-no-runtime
      uses: actions/upload-artifact@v3
      with:
        name: jboxtransfer-x64-portable-no-runtime
        path: ./JboxTransfer.WPF/bin/Release/net7.0-windows/

    - name: Build Self-Contained
      run: dotnet publish JboxTransfer.WPF/JboxTransfer.WPF.csproj -c Release -f net7.0-windows --self-contained
    - name: Delete Extra Files
      run: |
          Remove-Item -Force -Recurse -Path "./JboxTransfer.WPF/bin/Release/net7.0-windows/win-x64/publish/cs"
          Remove-Item -Force -Recurse -Path "./JboxTransfer.WPF/bin/Release/net7.0-windows/win-x64/publish/de"
          Remove-Item -Force -Recurse -Path "./JboxTransfer.WPF/bin/Release/net7.0-windows/win-x64/publish/es"
          Remove-Item -Force -Recurse -Path "./JboxTransfer.WPF/bin/Release/net7.0-windows/win-x64/publish/fr"
          Remove-Item -Force -Recurse -Path "./JboxTransfer.WPF/bin/Release/net7.0-windows/win-x64/publish/it"
          Remove-Item -Force -Recurse -Path "./JboxTransfer.WPF/bin/Release/net7.0-windows/win-x64/publish/ja"
          Remove-Item -Force -Recurse -Path "./JboxTransfer.WPF/bin/Release/net7.0-windows/win-x64/publish/ko"
          Remove-Item -Force -Recurse -Path "./JboxTransfer.WPF/bin/Release/net7.0-windows/win-x64/publish/pl"
          Remove-Item -Force -Recurse -Path "./JboxTransfer.WPF/bin/Release/net7.0-windows/win-x64/publish/pt-BR"
          Remove-Item -Force -Recurse -Path "./JboxTransfer.WPF/bin/Release/net7.0-windows/win-x64/publish/ru"
          Remove-Item -Force -Recurse -Path "./JboxTransfer.WPF/bin/Release/net7.0-windows/win-x64/publish/tr"
    - name: Pack
      run: iscc ./Installer/jboxtransfer-noruntime.iss

    - name: Upload jboxtransfer-x64-installer-offline
      uses: actions/upload-artifact@v3
      with:
        name: jboxtransfer-x64-installer-offline
        path: ./Installer/jboxtransfer-x64-installer-offline.exe

    - name: Upload jboxtransfer-x64-portable-with-runtime
      uses: actions/upload-artifact@v3
      with:
        name: jboxtransfer-x64-portable-with-runtime
        path: ./JboxTransfer.WPF/bin/Release/net7.0-windows/win-x64/publish/
