name: Build WPF App
on:
  workflow_dispatch:
jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.x
    - name: Download & install Scoop
      run: | 
          iex "& {$(irm get.scoop.sh)} -RunAsAdmin"
          Join-Path (Resolve-Path ~).Path "scoop\shims" >> $Env:GITHUB_PATH
          scoop bucket add extras
    - name: Download & install dependencies
      run: scoop install inno-setup 7zip

    - name: Build
      run: dotnet build JboxTransfer.WPF/JboxTransfer.WPF.csproj -c Release -f net7.0-windows
    - name: Pack
      run: iscc ./Installer/jboxtransfer.iss
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3.1.0
      with:
        name: jboxtransfer-x64-installer
        path: ./Installer/mysetup.exe
